### ISSUE TITLE
SonaSet not working

### ISSUE THREAD

**Issue by Noelwiz** [AurorusFur/FurryRoleplay#1]
I have the plugin running on a server, using CraftBuckkit Spiggot, as hopefully shown bellow

![image](https://user-images.githubusercontent.com/34178419/123730548-5f6c1e00-d84b-11eb-9444-a563fd67e541.png)

we do have a number of other plugins, but hopefully they're not the root cause
![image](https://user-images.githubusercontent.com/34178419/123731065-4fa10980-d84c-11eb-954a-3ae8d40e1dc7.png)

**These commands arent working**
/wardrobe
/setsona
/social

The only error text I get is "An Internal Error Occurred while attempting to preform this command"

/infosona works
![image](https://user-images.githubusercontent.com/34178419/123731152-74957c80-d84c-11eb-8351-6c0d31360da1.png)

#
#  SkinsRestorer Config.yml  #
#  Generated on 13.7.2       #

**Comment by AurorusFur** [comment]
Can you show full error?

**Comment by Noelwiz** [comment]
Well I just started updating from 1.17 to 1.17.1 and it's working. So I guess it was either a problem with a beta version of paper or spigot, or something.
